[package]
name = "neritigen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.4"
winit = "0.25.0"

ng_render = { path = "../ng_render" }
